name: parser CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CONFIG_FILE_PATH: ./conf/conf.env
  BASE_URL: https://api.aiven.io

jobs:
  test_parser:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: python_setup
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: install_dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # create a temporary config file to test main.py
    # get vars and secrets from github
    - name: set_config
      run: |
        cat <<EOF > $CONFIG_FILE_PATH
        #!/bin/bash
        PROJECT=${{ vars.PROJECT }}
        TOKEN=${{ secrets.TOKEN }}
        BASE_URL=$BASE_URL
        EOF

    # run main script
    - name: run_main
      run: |
        python main.py
    # check that the main script created the files as expected
    - name: test_main
      run: |
        file_name="graph_data.dot"
        [[ -f ./$file_name ]] && echo "$file_name created - OK" || exit 1
        file_name="graph_data.gml"
        [[ -f ./$file_name ]] && echo "$file_name created - OK" || exit 1
        file_name="nx.html"
        [[ -f ./$file_name ]] && echo "$file_name created - OK" || exit 1

    # run app script
    - name: run_app
      run: |
        python app.py &
    # check that the app is reachable
    - name: test_app
      run: |
        head=$(curl --head http://127.0.0.1:8050/ | head -n 1)
        [[ $head = *"200 OK"* ]] && echo "$head" || exit 1


  do_something_else:
    runs-on: ubuntu-latest
    needs: test_parser
    steps:
    - run: echo "Doing something else"
